# Generated by Django 4.2 on 2025-06-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('Año_de_Publicación', models.IntegerField()),
                ('Director', models.CharField(max_length=40)),
                ('País', models.CharField(max_length=40)),
                ('Género', models.CharField(max_length=40)),
                ('Sinopsis', models.CharField(max_length=500)),
            ],
        ),
    ]
