# Generated by Django 4.2 on 2025-06-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gore',
            name='Sinopsis',
            field=models.TextField(max_length=500),
        ),
    ]
