# Generated by Django 4.2 on 2025-06-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_gore_sinopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='gore',
            name='Picture',
            field=models.ImageField(null=True, upload_to='movies_images'),
        ),
    ]
