# Generated by Django 4.2 on 2025-06-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_gore_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='gore',
            name='TrailerURL',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
