# Generated by Django 4.2 on 2025-06-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_gore_trailerurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='gore',
            name='Clasificacion',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gore',
            name='Duracion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gore',
            name='Rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gore',
            name='Tags',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
